### ISSUE TITLE
Filtering search results for cases

### ISSUE THREAD

**Issue by pierrecagne** [npolar/placenames#15]
If one were to add `v2params.set("facet", "area")` in `src/cases-search/cases-search-url.js`, one would have the filter for areas under the seqrch box in the 'case' tab of the application. However, no fetch request is done when clicking on a filter value, which result in the page staying as such (no rerender triggered by the change of the list of results).

This is strange because the case search tab follows the same exact recipe than the placename search tab, based on the same SearchAny lit-element... I can't understand the bug after half a day trying to track it. All I know is that: 

1. the url of the webpage is correctly modified
2. if reloading the page after clicking a filter, one gets the expected ouputs (so I would say routing is not in question)
3. the method this.searchURL is only triggered at connectedCallback, but not when clicking a filter value
4. the API is not fetch after clicking a filter value
5. the exact same actions on the placename tab has the expected results...

Because it is working on the placename tab, I want to dismiss the possibility that the bug is in SearchAny. But the CaseEdit lit-element is then so simple that the solution should be obvious.

**Comment by cnrdh** [comment]
Welcome, this bit me too and its indeed nasty. My hunch is that it's related to routing, I would try a naked case search (letting case be the default instead of names) and see if that worked...

**Comment by pierrecagne** [comment]
Ok, this is indeed a routing issue. If I change from 
```js
path: '/sak',
component: 'cases-search'
```
to
```js
path: '/sak',
action: () => new CasesSearch()
```
everything works ok! Something mysterious with vadiin router?

**Comment by cnrdh** [comment]
Amazing that this worked...
